# Generated by Django 4.2.7 on 2023-11-26 08:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_rename_bia_profile_bio_profile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images/')),
                ('post', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
